# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: req_DH_params.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13req_DH_params.proto\"U\n\x0f\x44HParamsRequest\x12\r\n\x05nonce\x18\x01 \x01(\t\x12\x14\n\x0cserver_nonce\x18\x02 \x01(\t\x12\x12\n\nmessage_id\x18\x03 \x01(\x05\x12\t\n\x01\x61\x18\x04 \x01(\t\"V\n\x10\x44HParamsResponse\x12\r\n\x05nonce\x18\x01 \x01(\t\x12\x14\n\x0cserver_nonce\x18\x02 \x01(\t\x12\x12\n\nmessage_id\x18\x03 \x01(\x05\x12\t\n\x01\x62\x18\x04 \x01(\t2H\n\x0f\x44HParamsService\x12\x35\n\x0eProcessRequest\x12\x10.DHParamsRequest\x1a\x11.DHParamsResponseB\x0cZ\n/DH_paramsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'req_DH_params_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\n/DH_params'
  _DHPARAMSREQUEST._serialized_start=23
  _DHPARAMSREQUEST._serialized_end=108
  _DHPARAMSRESPONSE._serialized_start=110
  _DHPARAMSRESPONSE._serialized_end=196
  _DHPARAMSSERVICE._serialized_start=198
  _DHPARAMSSERVICE._serialized_end=270
# @@protoc_insertion_point(module_scope)
