version: '3'
volumes:
  db_data:
  redis_data:

networks:
  default:
    external:
      name: webhw1_default

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - auth-services1
      - auth_service2
      - biz_service1
      - biz_service2
    # networks:
    #   - webhw1_default

  auth-services1:
    image: authservice1:v1
    ports:
      - "8000:8000"
    depends_on:
      - redis
    # networks:
    #   - webhw1_default

  auth_service2:
    image: authservice2:v1
    ports:
      - "8001:8000"
    depends_on:
      - redis
    # networks:
    #   - webhw1_default


  biz_service1:
    image: bizservice1:v1
    ports:
      - "8002:8000"
    depends_on:
      - db
      - redis

    # networks:
    #   - webhw1_default

  biz_service2:
    image: bizservice2:v1
    ports:
      - "8003:8000"
    depends_on:
      - db
      - redis
    # networks:
    #   - webhw1_default
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: web_HW1
    volumes:
      - db_data:/var/lib/postgresql/data


