version: '3'
volumes:
  db_data:
  redis_data:

networks:
  webhw1_default:
    external:
      name: webhw1_default

services:
  gateway:
    image: gateeway:v1
    ports:
      - "80:80"
    depends_on:
      - auth_services1
      - auth_service2
      - biz_service1
      - biz_service2
    networks:
      - webhw1_default
#//////////////////////////////////////////
  auth_services1:
    image: authservice1:v2
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=webhw1_redis_1
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - webhw1_default
#//////////////////////////////////////////
  auth_service2:
    image: authservice2:v1
    ports:
      - "8001:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=webhw1_redis_1
      - REDIS_PORT=6379
    networks:
      - webhw1_default

#/////////////////////////////////////////
  biz_service1:
    image: bizservice1:v5
    ports:
      - "8002:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_USER=kamyar
      - DB_NAME=kamyardb
    networks:
      - webhw1_default
#/////////////////////////////////////////
  biz_service2:
    image: bizservice2:v4
    ports:
      - "8003:8000"
    depends_on:
      - db
      - redis
    networks:
      - webhw1_default
    environment:
      - DB_HOST=db
      - DB_USER=kamyar
      - DB_NAME=kamyardb
      
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  
    networks:
      - webhw1_default

  db:
    image: postgres
    environment:
      POSTGRES_USER: kamyar
      POSTGRES_PASSWORD: karsanj1380
      POSTGRES_DB: kamyardb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - webhw1_default
