# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_users.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fget_users.proto\"^\n\x05Userr\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x66\x61mily\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\x12\x0b\n\x03sex\x18\x05 \x01(\t\x12\x11\n\tcreatedAt\x18\x06 \x01(\t\"Z\n\x0eGetDataRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08\x61uth_key\x18\x02 \x01(\x0c\x12\x12\n\nmessage_id\x18\x03 \x01(\x05\x12\x11\n\tredis_key\x18\x04 \x01(\t\"C\n\x0fGetDataResponse\x12\x1c\n\x0creturn_users\x18\x01 \x03(\x0b\x32\x06.Userr\x12\x12\n\nmessage_id\x18\x02 \x01(\x05\x32;\n\tget_users\x12.\n\x07GetData\x12\x0f.GetDataRequest\x1a\x10.GetDataResponse\"\x00\x42\rZ\x0bget_user/pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_users_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\013get_user/pb'
  _USERR._serialized_start=19
  _USERR._serialized_end=113
  _GETDATAREQUEST._serialized_start=115
  _GETDATAREQUEST._serialized_end=205
  _GETDATARESPONSE._serialized_start=207
  _GETDATARESPONSE._serialized_end=274
  _GET_USERS._serialized_start=276
  _GET_USERS._serialized_end=335
# @@protoc_insertion_point(module_scope)
