# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import req_DH_params_pb2 as req__DH__params__pb2


class DHParamsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessRequest = channel.unary_unary(
                '/DHParamsService/ProcessRequest',
                request_serializer=req__DH__params__pb2.DHParamsRequest.SerializeToString,
                response_deserializer=req__DH__params__pb2.DHParamsResponse.FromString,
                )


class DHParamsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DHParamsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessRequest,
                    request_deserializer=req__DH__params__pb2.DHParamsRequest.FromString,
                    response_serializer=req__DH__params__pb2.DHParamsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DHParamsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DHParamsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DHParamsService/ProcessRequest',
            req__DH__params__pb2.DHParamsRequest.SerializeToString,
            req__DH__params__pb2.DHParamsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
