info:
  contact: {}
paths:
  /gateway/get_users/{user_id}:
    get:
      consumes:
      - application/json
      description: Get user information by ID
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Get user by ID
      tags:
      - Users
  /gateway/get_users_with_sql_inject/{user_id}:
    get:
      consumes:
      - application/json
      description: Get user information by ID with injection sql
      parameters:
      - description: user_id
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Get user by ID with sql injection
      tags:
      - Users_injection_sql
swagger: "2.0"
